prompt --application/pages/page_00022
begin
--   Manifest
--     PAGE: 00022
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>1800582798131282
,p_default_application_id=>106
,p_default_id_offset=>0
,p_default_owner=>'INTERN'
);
wwv_flow_imp_page.create_page(
 p_id=>22
,p_name=>'About BiteByte'
,p_alias=>'ABOUT-BITEBYTE'
,p_step_title=>'About BiteByte'
,p_autocomplete_on_off=>'OFF'
,p_javascript_code_onload=>wwv_flow_string.join(wwv_flow_t_varchar2(
'function showToast() {',
'  const toast = document.getElementById("toast");',
'  toast.classList.add("show");',
'  setTimeout(() => toast.classList.remove("show"), 3000);',
'}',
''))
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/* General reset for this page */',
'body {',
'  margin: 0;',
'  padding: 0;',
'  overflow-x: hidden;',
'  background: radial-gradient(circle at top left, #1f2937, #111827);',
'  font-family: ''Poppins'', sans-serif;',
'  color: #fff;',
'}',
'',
'/* Center container */',
'.bb-container {',
'  display: flex;',
'  align-items: center;',
'  justify-content: center;',
'  height: 80vh;',
'}',
'',
'/* Glass card */',
'.bb-card {',
'  background: rgba(255, 255, 255, 0.07);',
'  backdrop-filter: blur(12px);',
'  padding: 20px 10px;',
'  border-radius: 20px;',
'  max-width: 700px;',
'  text-align: center;',
'  box-shadow: 0 8px 30px rgba(0, 0, 0, 0.4);',
'  animation: fadeIn 0.8s ease-in-out;',
'}',
'',
'/* Logo */',
'.bb-logo {',
'  width: 90px;',
'  margin-bottom: 15px;',
'}',
'',
'/* Title */',
'.bb-card h1 {',
'  font-size: 2.3em;',
'  margin: 10px 0;',
'  color: #fff;',
'}',
'.bb-card h1 span {',
'  color: #00d0ff;',
'}',
'',
'/* Paragraph */',
'.bb-card p {',
'  font-size: 1.05em;',
'  color: #cfcfcf;',
'  line-height: 1.6;',
'  margin-bottom: 25px;',
'}',
'',
'/* Features */',
'.bb-features {',
'  text-align: left;',
'  margin-top: 15px;',
'}',
'.bb-feature {',
'  background: rgba(255, 255, 255, 0.08);',
'  border-left: 4px solid #00d0ff;',
'  border-radius: 8px;',
'  padding: 12px 16px;',
'  margin-bottom: 10px;',
'  transition: transform 0.2s ease;',
'}',
'.bb-feature:hover {',
'  transform: scale(1.02);',
'}',
'',
'/* Button */',
'.bb-btn {',
'  background: linear-gradient(90deg, #00c3ff, #0072ff);',
'  border: none;',
'  color: white;',
'  padding: 12px 28px;',
'  font-size: 1em;',
'  border-radius: 8px;',
'  cursor: pointer;',
'  margin-top: 25px;',
'  transition: 0.3s;',
'}',
'.bb-btn:hover {',
'  transform: translateY(-3px);',
'  background: linear-gradient(90deg, #0072ff, #00c3ff);',
'}',
'',
'/* Toast */',
'#toast {',
'  visibility: hidden;',
'  background: #00c3ff;',
'  color: white;',
'  border-radius: 8px;',
'  padding: 12px 18px;',
'  position: fixed;',
'  bottom: 35px;',
'  right: 30px;',
'  opacity: 0;',
'  transition: all 0.5s;',
'}',
'#toast.show {',
'  visibility: visible;',
'  opacity: 1;',
'  bottom: 50px;',
'}',
'',
'/* Animation */',
'@keyframes fadeIn {',
'  from {opacity: 0; transform: translateY(20px);}',
'  to {opacity: 1; transform: translateY(0);}',
'}',
'',
'/* --- FEATURE ROW --- */',
'.bb-feature-row {',
'  display: flex;',
'  justify-content: center;',
'  align-items: center;',
'  gap: 18px;',
'  margin-top: 30px;',
'  margin-bottom: 10px;',
'  flex-wrap: nowrap;',
'  overflow: hidden;',
'  padding: 0 10px;',
'  position: relative;',
'}',
'',
'/* --- FEATURE CARD --- */',
'.bb-feature-card {',
'  background: rgba(255, 255, 255, 0.08);',
'  backdrop-filter: blur(8px);',
'  border-radius: 12px;',
'  width: 300px;',
'  min-height: 115px;',
'  padding: 14px 12px;',
'  text-align: center;',
'  border-top: 3px solid #00bfff;',
'  box-shadow: 0 3px 10px rgba(0, 0, 0, 0.25);',
'  transition: all 0.25s ease;',
'  transform: scale(1);',
'  transform-origin: center;',
'  overflow: hidden;',
'  position: relative;',
'  z-index: 0; /* Ensures all start at same layer */',
'}',
'',
'/* --- CONSISTENT HOVER EFFECT --- */',
'.bb-feature-card:hover {',
'  transform: translateY(-1px);',
'  background: rgba(0, 191, 255, 0.10);',
'  box-shadow: 0 0 16px rgba(0, 191, 255, 0.45);',
'  border-top-color: #00bfff;',
'  z-index: 5; /* Lifted above siblings without overlapping tint */',
'}',
'',
'/* --- TEXT --- */',
'.bb-feature-card h3 {',
'  color: #00bfff;',
'  margin-bottom: 8px;',
'  font-size: 1.05em;',
'  font-weight: 600;',
'}',
'',
'.bb-feature-card p {',
'  color: #cccccc;',
'  font-size: 0.9em;',
'  line-height: 1.4;',
'  margin: 0;',
'}',
'',
'/* --- EQUAL HEIGHT ALIGNMENT --- */',
'.bb-feature-card {',
'  display: flex;',
'  flex-direction: column;',
'  justify-content: center;',
'}',
'',
'/* --- RESPONSIVE --- */',
'@media (max-width: 650px) {',
'  .bb-feature-row {',
'    flex-wrap: wrap;',
'  }',
'  .bb-feature-card {',
'    width: 80%;',
'    margin-bottom: 12px;',
'  }',
'}',
''))
,p_step_template=>2979075366320325194
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'11'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(23338066368293108)
,p_plug_name=>'BiteByte'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>4501440665235496320
,p_plug_display_sequence=>10
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div class="bb-container">',
'  <div class="bb-card">',
'    <img class="bb-logo" src="#APP_IMAGES#app-106-logo.png" alt="BiteByte Logo">',
'    <h1>Welcome to <span>BiteByte</span></h1>',
'    <p>',
'      <b>Hungry for smarter meal management? </b>',
'      ',
'      BiteByte serves up the perfect recipe.',
'      <br>',
'      Plan meals, Balance budgets, and Track costs effortlessly.',
'      <br>',
'      Cooked to perfection by Phoenix, where great ideas rise just like great meals. </p>',
'',
'    <div class="bb-feature-row">',
'    <div class="bb-feature-card">',
'        <h3>Smart Menu</h3>',
'        <p>Plan daily meals and track real-time costs</p>',
'    </div>',
'',
'    <div class="bb-feature-card">',
'        <h3>Budget Insights</h3>',
'        <p>Balance employee and company contributions</p>',
'    </div>',
'',
'    <div class="bb-feature-card">',
'        <h3>Transparency</h3>',
'        <p>View your meal history and deductions</p>',
'    </div>',
'    </div>',
'',
'',
'    <button class="bb-btn" onclick="showToast()">Explore More</button>',
'  </div>',
unistr('  <div id="toast">Coming soon \2014 new BiteByte features \D83C\DF54</div>'),
'</div>',
''))
,p_ai_enabled=>false
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp.component_end;
end;
/
