------------------------------------------------------------
-- Trigger: TRG_PHOENIX_ATTENDANCE_MONTH_YEAR
-- Purpose: Maintain MONTH_VALUE based on ATTENDANCE_DATE (Duplicate Safety)
------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_PHOENIX_ATTENDANCE_MONTH_YEAR
BEFORE INSERT OR UPDATE ON PHOENIX_DAILY_ATTENDANCE
FOR EACH ROW
BEGIN
  IF :NEW.ATTENDANCE_DATE IS NOT NULL THEN
    :NEW.MONTH_VALUE := EXTRACT(MONTH FROM :NEW.ATTENDANCE_DATE);
  END IF;
END;
/
ALTER TRIGGER TRG_PHOENIX_ATTENDANCE_MONTH_YEAR ENABLE;
