------------------------------------------------------------
-- 01_tables.sql
-- Core table definitions for the B1TEBYTE Meal Management DB
------------------------------------------------------------

CREATE TABLE PHOENIX_CALENDAR_MASTER
(
    CAL_DATE        DATE,
    CAL_WHLD        VARCHAR2(1),
    CAL_HLD_STATUS  VARCHAR2(30),
    CONSTRAINT PK_PHOENIX_CALENDAR_MASTER PRIMARY KEY (CAL_DATE)
);

CREATE TABLE PHOENIX_DAILY_ATTENDANCE
(
    ATTENDANCE_ID     VARCHAR2(10),
    ATTENDANCE_DATE   DATE NOT NULL,
    EMP_CODE          VARCHAR2(15) NOT NULL,
    IS_TAKING_LUNCH   VARCHAR2(3) DEFAULT 'Y',
    IS_TAKING_DINNER  VARCHAR2(3) DEFAULT 'N',
    USER_ID           VARCHAR2(50),
    ENTRY_DATE        DATE DEFAULT SYSDATE,
    LAST_UPDATE       VARCHAR2(20),
    LAST_UPDATE_DATE  DATE,
    MONTH_VALUE       NUMBER(2,0),
    CONSTRAINT PK_PHOENIX_DAILY_ATTENDANCE PRIMARY KEY (ATTENDANCE_ID)
);

CREATE TABLE PHOENIX_DAILY_BUDGET_TRACKER
(
    TRACK_ID          VARCHAR2(10),
    MEAL_DATE         DATE NOT NULL,
    TOTAL_LUNCH_COUNT NUMBER(10,0),
    TOTAL_DINNER_COUNT NUMBER(10,0),
    TOTAL_MEALS       NUMBER(10,0),
    DAILY_MEAL_COST   NUMBER(10,2),
    COMPANY_SHARE     NUMBER(10,2),
    EMPLOYEE_SHARE    NUMBER(10,2),
    AVAILABLE_BUDGET  NUMBER(10,2),
    REMAINING_BUDGET  NUMBER(10,2),
    EXTRA_COST        NUMBER(10,2),
    USER_ID           VARCHAR2(10),
    ENTRY_DATE        DATE DEFAULT SYSDATE,
    LAST_UPDATE       VARCHAR2(20),
    LAST_UPDATE_DATE  DATE,
    MONTH             NUMBER(2,0),
    YEAR              NUMBER(4,0),
    CONSTRAINT PK_PHOENIX_DAILY_BUDGET_TRACKER PRIMARY KEY (TRACK_ID)
);

CREATE TABLE PHOENIX_DAILY_EMPLOYEE_INFORMATION
(
    EMPLOYEE_ID       VARCHAR2(10),
    EMP_CODE          VARCHAR2(30) NOT NULL,
    DATE_VALUE        DATE,
    MONTH_VALUE       NUMBER(2,0),
    YEAR_VALUE        NUMBER(4,0),
    TOTAL_MEALS       NUMBER(10,0) DEFAULT 0,
    PER_MEAL_COST     NUMBER(10,2) DEFAULT 0,
    TOTAL_MEAL_COST   NUMBER(10,2),
    DUE               NUMBER(10,2) DEFAULT 0,
    USER_ID           VARCHAR2(10),
    ENTER_DATE        DATE DEFAULT SYSDATE,
    LAST_UPDATE       VARCHAR2(20),
    LAST_UPDATE_DATE  DATE,
    CONSTRAINT PK_PHOENIX_DAILY_EMPLOYEE_INFORMATION PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE PHOENIX_DAILY_MEAL_ITEM
(
    ITEM_ID           VARCHAR2(10),
    MEAL_DATE         DATE NOT NULL,
    MENU_ID           VARCHAR2(10) NOT NULL,
    TOTAL_COST        NUMBER(10,2),
    USER_ID           VARCHAR2(10),
    ENTRY_DATE        DATE DEFAULT SYSDATE,
    LAST_UPDATE       VARCHAR2(20),
    LAST_UPDATE_DATE  DATE,
    CONSTRAINT PK_PHOENIX_DAILY_MEAL_ITEM PRIMARY KEY (ITEM_ID)
);

CREATE TABLE PHOENIX_GUEST_MEAL_TRACKER
(
    GUEST_ID              VARCHAR2(15),
    EMP_CODE              VARCHAR2(20) NOT NULL,
    GUEST_DATE            DATE NOT NULL,
    GUEST_NAME            VARCHAR2(100),
    GUEST_COUNT           NUMBER(5,0),
    PER_MEAL_COST         NUMBER(12,2) DEFAULT 0,
    TOTAL_GUEST_MEAL_COST NUMBER(12,2) DEFAULT 0,
    USER_ID               VARCHAR2(10),
    ENTRY_DATE            DATE DEFAULT SYSDATE,
    LAST_UPDATE           VARCHAR2(50),
    LAST_UPDATE_DATE      DATE,
    CONSTRAINT PK_PHOENIX_GUEST_MEAL_TRACKER PRIMARY KEY (GUEST_ID)
);

CREATE TABLE PHOENIX_HR_EMP_MASTER
(
    EMP_CODE      VARCHAR2(30),
    EMP_NAME      VARCHAR2(100) NOT NULL,
    AREA_TYPE     VARCHAR2(11),
    STATUS_NAME   VARCHAR2(100),
    USER_ID       VARCHAR2(50),
    LUNCH_PREF    VARCHAR2(3) DEFAULT 'Y',
    DINNER_PREF   VARCHAR2(3) DEFAULT 'N',
    CONSTRAINT PK_PHOENIX_HR_EMP_MASTER PRIMARY KEY (EMP_CODE)
);

CREATE TABLE PHOENIX_MEAL_MANAGER
(
    MANAGER_ID            VARCHAR2(10),
    EMP_CODE              VARCHAR2(30) NOT NULL,
    MONTH                 NUMBER(2,0) NOT NULL,
    YEAR                  NUMBER(4,0) NOT NULL,
    PERIOD_KEY            VARCHAR2(6),
    USER_ID               VARCHAR2(10),
    ENTRY_DATE            DATE DEFAULT SYSDATE,
    LAST_UPDATE           VARCHAR2(20),
    LAST_UPDATE_DATE      DATE,
    EMPLOYEE_CONTRIBUTION NUMBER(10,2) DEFAULT 0,
    COMPANY_CONTRIBUTION  NUMBER(10,2) DEFAULT 0,
    CONSTRAINT PK_PHOENIX_MEAL_MANAGER PRIMARY KEY (MANAGER_ID)
);

CREATE TABLE PHOENIX_MENU
(
    MENU_ID          VARCHAR2(10),
    MENU_NAME        VARCHAR2(50) NOT NULL,
    DESCRIPTION      VARCHAR2(200),
    USER_ID          VARCHAR2(10),
    ENTRY_DATE       DATE DEFAULT SYSDATE,
    LAST_UPDATE      VARCHAR2(20),
    LAST_UPDATE_DATE DATE,
    CONSTRAINT PK_PHOENIX_MENU PRIMARY KEY (MENU_ID)
);

CREATE TABLE PHOENIX_MENU_ITEM_MAP
(
    MAP_ID           VARCHAR2(10),
    MENU_ID          VARCHAR2(10) NOT NULL,
    PRODUCT_ID       VARCHAR2(10) NOT NULL,
    UOM_ID           VARCHAR2(10) NOT NULL,
    QUANTITY         NUMBER(10,2) DEFAULT 0,
    COST             NUMBER(10,2) DEFAULT 0,
    USER_ID          VARCHAR2(10),
    ENTRY_DATE       DATE DEFAULT SYSDATE,
    LAST_UPDATE      VARCHAR2(20),
    LAST_UPDATE_DATE DATE,
    CONSTRAINT PK_PHOENIX_MENU_ITEM_MAP PRIMARY KEY (MAP_ID)
);

CREATE TABLE PHOENIX_MONTHLY_BUDGET
(
    BUDGET_ID             VARCHAR2(10),
    BUDGET_DATE           DATE NOT NULL,
    EMPLOYEE_CONTRIBUTION NUMBER(12,2) DEFAULT 0,
    COMPANY_CONTRIBUTION  NUMBER(12,2) DEFAULT 0,
    EXTRA_DEDUCTION       NUMBER(12,2) DEFAULT 0,
    TOTAL_EXPENSE         NUMBER(12,2) DEFAULT 0,
    USER_ID               VARCHAR2(10),
    ENTRY_DATE            DATE DEFAULT SYSDATE,
    LAST_UPDATE           VARCHAR2(50),
    LAST_UPDATE_DATE      DATE,
    MONTH                 NUMBER(2,0),
    YEAR                  NUMBER(4,0),
    TOTAL_MEALS           NUMBER(10,0),
    CONSTRAINT PK_PHOENIX_MONTHLY_BUDGET PRIMARY KEY (BUDGET_ID)
);

CREATE TABLE PHOENIX_PARTICIPANTS
(
    REQUEST_ID      VARCHAR2(10),
    EMP_CODE        VARCHAR2(10) NOT NULL,
    MEAL_DATE       DATE NOT NULL,
    DAY_TYPE        VARCHAR2(20),
    LUNCH_REQUEST   VARCHAR2(3) DEFAULT 'Yes',
    DINNER_REQUEST  VARCHAR2(3) DEFAULT 'No',
    IS_ACTIVE       VARCHAR2(3) DEFAULT 'Yes',
    USER_ID         VARCHAR2(10),
    ENTRY_DATE      DATE DEFAULT SYSDATE,
    LAST_UPDATE     VARCHAR2(20),
    LAST_UPDATE_DATE DATE,
    CONSTRAINT PK_PHOENIX_PARTICIPANTS PRIMARY KEY (REQUEST_ID),
    CHECK (DAY_TYPE IN ('Working Day','Holiday','Weekend')),
    CHECK (LUNCH_REQUEST IN ('Yes','No')),
    CHECK (DINNER_REQUEST IN ('Yes','No')),
    CHECK (IS_ACTIVE IN ('Yes','No'))
);

CREATE TABLE PHOENIX_PRODUCT
(
    PRODUCT_ID      VARCHAR2(10),
    PRODUCT_NAME    VARCHAR2(100) NOT NULL,
    CATEGORY_NAME   VARCHAR2(100),
    UOM_ID          VARCHAR2(10) NOT NULL,
    USER_ID         VARCHAR2(10),
    ENTRY_DATE      DATE DEFAULT SYSDATE,
    LAST_UPDATE     VARCHAR2(20),
    LAST_UPDATE_DATE DATE,
    CONSTRAINT PK_PHOENIX_PRODUCT PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE PHOENIX_UOM
(
    UOM_ID          VARCHAR2(10),
    UOM_FULL_NAME   VARCHAR2(50) NOT NULL,
    UOM_SHORT_NAME  VARCHAR2(50) NOT NULL,
    USER_ID         VARCHAR2(10),
    ENTRY_DATE      DATE DEFAULT SYSDATE,
    LAST_UPDATE     VARCHAR2(20),
    LAST_UPDATE_DATE DATE,
    CONSTRAINT PK_PHOENIX_UOM PRIMARY KEY (UOM_ID)
);
